export const distritosSantaCruz = [
  ["", "Selecciona distrito", true],
  ["254", "ASCENCION DE GUARAYOS"],
  ["212", "AYACUCHO (C. PORONGO)"],
  ["233", "BOYUIBE"],
  ["219", "BUENA VISTA"],
  ["229", "CABEZAS"],
  ["232", "CAMIRI"],
  ["228", "CHARAGUA"],
  ["250", "COMARAPA"],
  ["246", "CONCEPCION"],
  ["211", "COTOCA"],
  ["293", "CUATRO CANADAS"],
  ["230", "CUEVO"],
  ["256", "EL PUENTE"],
  ["214", "EL TORNO"],
  ["244", "GENERAL SAAVEDRA"],
  ["231", "GUTIERREZ"],
  ["213", "LA GUARDIA"],
  ["227", "LAGUNILLAS"],
  ["241", "MAIRANA"],
  ["245", "MINEROS"],
  ["243", "MONTERO"],
  ["236", "MORO MORO"],
  ["260", "OKINAWA"],
  ["223", "PAILON"],
  ["240", "PAMPA GRANDE"],
  ["263", "PLAN TRES MIL"],
  ["225", "PORTACHUELO"],
  ["237", "POSTRER VALLE"],
  ["238", "PUCARA"],
  ["253", "PUERTO QUIJARRO"],
  ["252", "PUERTO SUAREZ"],
  ["242", "QUIRUSILLAS"],
  ["224", "ROBORE"],
  ["251", "SAIPINA"],
  ["239", "SAMAIPATA"],
  ["262", "SAN ANTONIO DE LOMERIO"],
  ["220", "SAN CARLOS"],
  ["216", "SAN IGNACIO (C. SAN IGNACIO DE VELASCO)"],
  ["247", "SAN JAVIER"],
  ["222", "SAN JOSE (C. SAN JOSE DE CHIQUITOS)"],
  ["261", "SAN JUAN DE YAPACANI"],
  ["248", "SAN JULIAN"],
  ["249", "SAN MATIAS"],
  ["217", "SAN MIGUEL (C. SAN MIGUEL DE VELASCO)"],
  ["218", "SAN RAFAEL"],
  ["257", "SANTA CRUZ 1"],
  ["258", "SANTA CRUZ 2"],
  ["259", "SANTA CRUZ 3"],
  ["226", "SANTA ROSA DEL SARA"],
  ["235", "TRIGAL"],
  ["255", "URUBICHA"],
  ["234", "VALLE GRANDE (C. JESUS DE VALLE GRANDE)"],
  ["215", "WARNES"],
  ["221", "YAPACANI"]
] as const;

export const distritosBeniPando = [
  ["901", "COBIJA"],
  ["902", "PORVENIR/BELLA FLOR"],
  ["903", "FILADELFIA/SAN PEDRO"],
  ["904", "BOLPEBRA"],
  ["905", "SANTA ROSA DEL ABUNA"],
  ["906", "PUERTO RICO"],
  ["907", "SENA"],
  ["908", "SAN LORENZO"],
  ["909", "PUERTO GONZALO MORENO"],
  ["910", "NUEVA ESPERANZA"]
] as const;

// Default distritosData for Santa Cruz (GilmarCh10)
export const distritosData = distritosSantaCruz;
